language: python
python:
#- "2.7"
- "3.7"
install:
- pip install Flask
- touch dbconfig.py
- ./setup.py develop
- pip install coveralls
- pybabel compile -f -d som_opendata/translations
script:
- nosetests
after_success:
- coveralls
